services:
  server: 
    build:
      context: server
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8080:8080'
    environment:
      - FLASK_ENV=development  # Enables auto-reloading
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    develop:
      watch:
      # Monitors the following file and copies the changes in the container
        - action: sync
          path: server/openface_server.py
          target: /app/openface_server.py
    networks: 
      - backend
    depends_on:
        - openface

  openface:
    image: algebr/openface:latest
    container_name: openface_container
    restart: always
    tty: true # Keeps the container running
    volumes:
      - images:/home/openface-build/images  # Mount local images folder
      - output:/home/openface-build/output  # Mount output folder
    networks:
      - backend

volumes:
  images:
  output:

networks:
  backend: