services:
  web: 
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8080:8080'
    # volumes:
    #   - .:/src  # Ensure live reload works
    environment:
      - FLASK_ENV=development  # Enables auto-reloading
    develop:
      watch:
      # Monitors the following file and copies the changes in the container
        - action: sync
          path: ./openface_server.py
          target: /home/app/openface_server.py